{% set name = "derivative" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 72e7fd56e92665f939b5449c4b9ceea88fdf02eda7378cf0a3e961ab0df58181

build:
  noarch: python
  number: 0
  # This package does not have a setup.py in the github repository but one is
  # generated in the tarball. The pyproject.toml file doesn't let a normal
  # setup.py installation work, so remove it.
  # Solution taken from: https://github.com/conda-forge/staged-recipes/pull/12652
  script: /bin/rm -f pyproject.toml && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python >=3.9
  run:
    - numpy >=1.18.3
    - python >=3.9
    - scikit-learn >=1.0.0
    - scipy >=1.4.1

test:
  imports:
    - derivative

about:
  home: https://github.com/andgoldschmidt/derivative
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: Numerical differentiation in python.
  doc_url: https://derivative.readthedocs.io
  dev_url: https://github.com/andgoldschmidt/derivative

extra:
  recipe-maintainers:
    - moorepants
