{% set name = "derivative" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4ce766a85a2d2cb65d7046ef4fdc953348a12b31809768df60b424a23090de27

build:
  noarch: python
  number: 0
  # This package does not have a setup.py in the github repository but one is
  # generated in the tarball. The pyproject.toml file doesn't let a normal
  # setup.py installation work, so remove it.
  # Solution taken from: https://github.com/conda-forge/staged-recipes/pull/12652
  script: /bin/rm -f pyproject.toml && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - numpy >=1.18.3
    - python >=3.7
    - scikit-learn
    - scipy >=1.4.1

test:
  imports:
    - derivative

about:
  home: https://github.com/andgoldschmidt/derivative
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: Numerical differentiation in python.
  doc_url: https://derivative.readthedocs.io
  dev_url: https://github.com/andgoldschmidt/derivative

extra:
  recipe-maintainers:
    - moorepants
